name: dartdelivery
description: Dartdelivery, dart web demo from github to heroku by drone.io
dependencies: 
  unittest: { sdk: unittest }
#  crimsonhttp: { git: https://github.com/chrisbu/CrimsonHttp.git }
